language: node_js
node_js:
  - node
script:
  - VUE_APP_GRAPHCMS_ENDPOINT=$GRAPHCMS_ENDPOINT VUE_APP_GRAPHCMS_AUTH=$GRAPHCMS_AUTH npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://redbarongames.co.uk --exclude "*.html" --region=eu-west-1 --acl public-read --cache-control max-age=31536000 --delete &&
    ~/.local/bin/aws s3 sync dist s3://redbarongames.co.uk --exclude "*" --include "*.html" --region=eu-west-1 --acl public-read --cache-control no-cache --delete
  skip_cleanup: true
  on:
    repo: RBrNx/RedbaronGames-v3
after_deploy: ~/.local/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /*
