language: node_js
node_js:
  - node
script:
  - npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://redbarongames.co.uk --region=eu-west-1 --acl public-read --delete
  skip_cleanup: true
  on:
    repo: RBrNx/RedbaronGames-v3
